---
    title: "Reproducible Research: Peer Assessment 1"
---

##Loading and preprocessing the data
data <- read.csv("activity.csv", header = TRUE, sep=',', 
                 na.strings="NA", nrows=17569)

##What is mean total number of steps taken per day?
steps_by_day <- aggregate(steps ~ date, data, sum)
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), 
     col="green", xlab="Number of Steps")
mean_steps_by_day <- mean(steps_by_day$steps)
median_steps_by_day <- median(steps_by_day$steps)

##What is the average daily activity pattern?
steps_by_interval <- aggregate(steps ~ interval, data, mean)
plot(steps_by_interval$interval, steps_by_interval$steps, type="l", xlab="Interval", 
     ylab="Number of Steps", main="Average Number of Steps per Day by Interval")
max_interval <- steps_by_interval[which.max(steps_by_interval$steps),1]

##Imputing missing values
NA_count <- nrow(subset(data, is.na(data$steps)))
incomplete <- sum(!complete.cases(data))
imputed_data <- transform(data, 
                          steps = ifelse(is.na(data$steps), 
                                         steps_by_interval$steps[match(data$interval, steps_by_interval$interval)], data$steps))
steps_by_date <- aggregate(steps ~ date, imputed_data, sum)
hist(steps_by_date$steps, main = paste("Total Steps Each Day"), 
     col="yellow", xlab="Number of Steps")
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), 
     col="green", xlab="Number of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("yellow", "green"), lwd=10)
mean_imputed <- mean(steps_by_date$steps)
median_imputed <- median(steps_by_date$steps)
mean_difference <- mean_imputed - mean_steps_by_day
median_difference <- median_imputed - median_steps_by_day
total_difference <- sum(steps_by_date$steps) - sum(steps_by_day$steps)

##Are there differences in activity patterns between weekdays and weekends?
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
imputed_data$dow = as.factor(ifelse(is.element(weekdays(as.Date(imputed_data$date)),
                                               weekdays), "Weekday", "Weekend"))
steps_by_interval_i <- aggregate(steps ~ interval + dow, imputed_data, mean)
library(lattice)
xyplot(steps_by_interval_i$steps ~ steps_by_interval_i$interval|steps_by_interval_i$dow, 
       main="Average Steps per Day by Interval",xlab="Interval", 
       ylab="Steps",layout=c(1,2), type="l")